
require 'uri'
require 'json'
require 'faraday'
require 'colorize'
require 'recursive-open-struct'

require_relative 'playon/version'
require_relative 'playon/helpers/helpers'
require_relative 'playon/web/client'
require_relative 'playon/kwallet/kwallet'
require_relative 'playon/auth/auth'
require_relative 'playon/videos/videos'
require_relative 'playon/config-file'
require_relative 'playon/playon'
